import AuthSession from '@/components/ui/pages/login/AuthSession'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AppBar from '@/components/ui/pages/login/AppBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'naver social sign-in by next-auth',
  description: 'Generated by create next app',
}

type Props = {
  children : React.ReactNode;
};

export default function RootLayout( { children }:Props ) {
  return (
    <html lang='en' className=''>
      <body>
        <header>
          <AppBar/>
        </header>
        <AuthSession>
          {children}
        </AuthSession>
      </body>
    </html>
  )
}
